# Generated by Django 3.1 on 2020-08-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Scheme name')),
                ('description', models.CharField(max_length=50, verbose_name='Description about the scheme')),
                ('registerationlink', models.CharField(max_length=50, verbose_name='Registration link')),
                ('pdflink', models.CharField(max_length=50, verbose_name='Pdf Link')),
            ],
        ),
    ]
