# Generated by Django 3.1 on 2020-08-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0002_auto_20200808_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='description',
            field=models.TextField(blank=True, max_length=250, verbose_name='Description about the scheme'),
        ),
    ]
