# Generated by Django 3.1 on 2020-08-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0004_auto_20200808_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='pdflink',
            field=models.CharField(blank=True, max_length=150, verbose_name='Pdf Link'),
        ),
        migrations.AlterField(
            model_name='info',
            name='registerationlink',
            field=models.CharField(blank=True, max_length=150, verbose_name='Registration link'),
        ),
    ]
