# Generated by Django 3.1 on 2020-08-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0006_comment_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='pdflink',
            field=models.CharField(blank=True, max_length=150, verbose_name='Brochure Link'),
        ),
    ]
